### ISSUE TITLE
Message "document uploaded successfully" appears before end of upload

### ISSUE THREAD

**Issue by fccoelho** [NAMD/pypln.web#21] opened 2012-12-30 11:17 UTC
@flavioamieiro : This message is appearing way too early. I found out by submitting a larger document which took many seconds to upload. 

So I suggest that we put first a message saying: "Document(s) uploading" and only when the page is refreshed the message about the successful upload should show up.

**Comment by flavioamieiro** [comment] 2012-12-30 15:58
This is strange. I really see no way this could happen, since we add messages to the user's message queue only after every document is processed. But any way, this code is being worked on right now and is definitely getting simpler. I'll keep this issue in mind and make sure I test the upload of a large file before I consider this done.

**Comment by flavioamieiro** [comment] 2013-01-10 17:43
I'll close this as "could not reproduce", and since this code changed a lot, it might as well be fixed. Please let me know if it happens again.

**Closed as completed by flavioamieiro** 2013-01-10 17:43 UTC
Labels: bug
